### ISSUE TITLE
Doesn't work with SASS, the output file is empty

### ISSUE THREAD

**Issue by seregap** [Nitive/postcss-extract#136]
Hello

The output file appears empty
- "postcss-loader": "^0.11.0"
- "sass-loader": "4.0.0"
- node: '5.3.0'

the webpack.config.js fragment is as follows:

``` javascript
module : {
        loaders : [{
            test   : /\.scss$/,
            loader : (ExtractTextPlugin.extract('style', 'css!postcss!sass', {  }))
    }]
    },
postcss: [
      require('postcss-extract')({
               extract: {
                 'important': path.join(__dirname, './test.css')
            }
      }),
]
```

**Comment by Nitive** [comment]
Could you please show sass file content? Just confugure webpack and everything works fine

**Comment by Nitive** [comment]
I added examples, check out `examples/` folder

**Comment by seregap** [comment]
sure, here you go 

**entry app.js**

``` javascript
'use strict';
var core = require('core.scss');
```

**core.scss**

``` css
@import 'modules/buttons';
```

**buttons.scss**

``` css
.button-group {
    width: 100%;
    display: table;
    table-layout: fixed;
    border-bottom: 1px solid $greyBorders;
    border-radius: 5px;
    overflow: hidden;
    .button {
        display: block;
        border-radius: 0;
        white-space: nowrap;
    }
    &__item {
        display: table-cell;
    }
    @important {
        display: inline-block;
    }
}  
```

**Comment by seregap** [comment]
well it seems we can't use custom @rules in sass, it is more likely a sass issue

**Comment by seregap** [comment]
@Nitive did you try it with sass-loader?

**Comment by Nitive** [comment]
@seregap Sass process `&` with at rules not correctly
![SassMeister screenshot](http://s.csssr.ru/2016-08-27-1257-hr20sxz5n4.png)

You can use extra braces

``` sass
@important {
  & {
    display: inline-block;
  }
}
```

**Comment by seregap** [comment]
@Nitive it won't be processed by postcss-extract anyway, as the @rule shuld be inside selector but not outside. This is a default behaviour for @rules in any CSS preprocessor including SASS (@rule bubbles up to the css root). It would be great to have an option to change the plugin logic if needed for such cases.

your code snippet above can be even simplyfied to be as follows, but it won't help

**input sass:**

``` css
.button-group {
  @important {
      display: inline-block;
  }
}
```

**output css:**

``` css
@important {
  .button-group {
    display: inline-block;
  }
}
```

**required by postcss-extract input css:**

``` css
.button-group {
  @important {
    display: inline-block;
  }
}
```
